// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using finance.datenbank;

#nullable disable

namespace finance.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20240330155656_DatumNeu")]
    partial class DatumNeu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("finance.Models.Benutzer", b =>
                {
                    b.Property<Guid>("BenutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Bargeld")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BenutzerId");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("finance.Models.Transaktion", b =>
                {
                    b.Property<Guid>("TransaktionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<Guid>("BenutzerId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("DatumZeit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Preis")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransaktionId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Transaktionen");
                });

            modelBuilder.Entity("finance.Models.Transaktion", b =>
                {
                    b.HasOne("finance.Models.Benutzer", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });
#pragma warning restore 612, 618
        }
    }
}
